//
//  problem_045.swift
//  project_euler
//
//  Created by Todd Olsen on 4/2/16.
//  Copyright © 2016 Todd Olsen. All rights reserved.
//

import Foundation

/*
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*/

func problem_045() -> Int {
    for n in (143 + 1)..<Int.max {
        let h = Int.hexagonalNumber(n)
        if h.isPentagonalNumber {
            return h
        }
    }
    fatalError()
}