//: Even Fibonacci numbers
/*:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

func problem_002() -> Int {
    
    var n1      = 1
    var n2      = 1
    var next    = 0
    var result  = 0
    
    repeat {
        next = n1 + n2
        n1 = n2
        n2 = next
        
        if next % 2 == 0 {
            result += next
        }
        
    } while next < 4_000_000
    
    return result
}